# https://leetcode.com/problems/find-the-difference/

# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Find the letter that was added in t.

# Example:

# Input:
# s = "abcd"
# t = "abcde"

# Output:
# e

# Explanation:
# 'e' is the letter that was added.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s = list(s)
        for i,each in enumerate(t):
            if s.count(t[i]) == 0:
                return t[i]
            else:
                s.pop(s.index(t[i]))
                continue
        